/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emicalculator;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javafx.scene.layout.Pane;

/**
 *
 * @author estudiante
 */
public class EjercicioGraphics extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioGraphics
     */
    public EjercicioGraphics() {
        initComponents();
    }

    @Override
    public void repaint(long time, int x, int y, int width, int height) {
        super.repaint(time, x, y, width, height); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
       
        //line 223 260, 476 153
        //line 476 153, 793 271
        //cuadrado grande 275 242,702 243,702 495,274 492
        
        this.getContentPane().setBackground(Color.white);
        g.setColor(Color.red);
        g.fillRect(60, 497, 812, 100);
        g.setColor(Color.BLUE);
        g.fillRect(274, 248, 430, 250);
        g.setColor(Color.BLACK);
        g.fillRect(336, 287, 100, 200);
        g.fillRect(532, 291, 100, 100);
        g.setColor(Color.BLACK);
        g.drawLine(183, 389, 183, 497);
        g.drawLine(796, 389, 796, 497);
        g.drawLine(223, 262, 477, 157);
        g.drawLine(477, 157, 793, 272);
        
        g.setColor(Color.YELLOW);
        g.fillOval(775, 333, 50, 50);
        g.setColor(Color.black);
        g.drawOval(775, 333, 50, 50);
        
        g.setColor(Color.YELLOW);
        g.fillOval(157, 333, 50, 50);
        g.setColor(Color.BLACK);
        g.drawOval(157, 333, 50, 50);
        
        g.setColor(Color.GREEN);
        int[] x={284,480,699,284};
        int[] y={242,158,240,242};
        g.fillPolygon(x, y, 4);
        g.setColor(Color.BLACK);
        
        
        g.fillRoundRect(416, 197, 100, 40, 20, 20);
        g.setColor(Color.WHITE);
        g.setFont(new Font("Times",Font.BOLD,20));
        g.drawString("Welcome", 425, 220);
        
        
               

        
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 812, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 620, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GraphicsDemo ventana = new GraphicsDemo();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioGraphics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
